[10.0][T991] - Added website_sale_comment_category_wise module
rfhk/cip-customization pull request #177
Opened 2020-05-11 06:18 UTC by YogeshMahera-SerpentCS

-  TASK #[991](https://www.quartile.co/web?#id=991&action=771&model=project.task&view_type=form&menu_id=505)

2020-05-11 06:24 UTC, YogeshMahera-SerpentCS commented
![download](https://user-images.githubusercontent.com/24264979/81530301-33a78380-937e-11ea-9e07-94f092f615ba.png)

2020-05-21 14:02 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 the Travis is going to fail due to other modules

2020-05-22 02:35 UTC, TimLai125 requested changes
Please remove the <data> tag in the xml files.

2020-05-25 02:54 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 Changes amended.

2020-05-27 06:08 UTC, TimLai125 requested changes
@YogeshMahera-SerpentCS Sorry for some comments may be a bit picky, but we want to keep the style nice and united.

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/__manifest__.py
> +    'description': """    """,
Remove `description`

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/__init__.py
> +from . import controllers
Add an empty line above `from . import controllers`

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/__manifest__.py
> +        'views/product_public_category_view.xml',
product_public_category_views.xml, please update the filename as well.

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/controllers/__init__.py
> +from . import main
Add an empty line above from . import controllers

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/controllers/main.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
LGPL

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/models/product_public_category.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
LGPL

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/views/product_public_category_view.xml
> +<odoo>
I think it is better to add `<?xml version="1.0" encoding="utf-8"?>` in v10.0

2020-05-27 06:08 UTC, TimLai125 commented on website_sale_comment_category_wise/views/templates.xml
> +<odoo>
I think it is better to add `<?xml version="1.0" encoding="utf-8"?>` in v10.0

2020-05-27 06:46 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 Changes amended.

2020-05-29 09:52 UTC, TimLai125 requested changes

2020-05-29 09:52 UTC, TimLai125 commented on website_sale_comment_category_wise/views/templates.xml
> +<?xml version="1.0" encoding="utf-8"?
<?xml version="1.0" encoding="utf-8"?>

2020-05-29 16:03 UTC, YogeshMahera-SerpentCS commented
Tested in local. working nicely 😊

2020-06-03 02:42 UTC, TimLai125 commented
@YogeshMahera-SerpentCS , Please run pre-commit on this PR.

2020-06-03 03:50 UTC, YogeshMahera-SerpentCS commented
Hi, @TimLai125 Actually the Travis is going to fail due to other modules.

2020-06-03 07:08 UTC, YogeshMahera-SerpentCS commented
Hi, @TimLai125 for test purpose I removed other modules and keep the only one module tried to run the pre-commit file, So it successfully passed. 
![rsz_screenshot_from_2020-06-03_12-31-02](https://user-images.githubusercontent.com/24264979/83606251-e5f5f380-a596-11ea-924d-af25ee443533.png)

2020-06-03 08:00 UTC, TimLai125 commented
> Hi, @TimLai125 for test purpose I removed other modules and keep the only one module tried to run the pre-commit file, So it successfully passed. Let me know if something miss?
> ![rsz_screenshot_from_2020-06-03_12-31-02](https://user-images.githubusercontent.com/24264979/83606251-e5f5f380-a596-11ea-924d-af25ee443533.png)

@YogeshMahera-SerpentCS This sounds strange, I expect the pre-commit command should at least complain about the missing readme files?

2020-06-03 08:45 UTC, YogeshMahera-SerpentCS commented
Hi, @TimLai125 yes Added Readme files. and I will also investigate the issue of why it's not getting a warning.

2020-06-04 02:44 UTC, merged