Adjust Email Templates, display timezone info
rfhk/cip-customization pull request #59
Opened 2017-07-19 06:36 UTC by TimLai125

2017-07-19 06:38 UTC, TimLai125 commented
This PR is ready for review

2017-07-19 07:06 UTC, yostashiro requested changes

2017-07-19 07:06 UTC, yostashiro commented on stock_delivery_notification/models/stock_picking.py
> +            picking.date_done_ctx = datetime_done_ctx.strftime("%Y-%m-%d %H:%M:%S %Z")
Can we use `to_string` method?

```
        for picking in self:
            if picking.date_done:
                fdt = fields.Datetime
                picking.date_done_ctx = fdt.to_string(fdt.context_timestamp(
                    picking, fdt.from_string(picking.date_done)))
```

2017-07-19 07:06 UTC, yostashiro commented on stock_delivery_notification/data/mail_template_data.xml
> +<p>If you have any queries, please reach us at sales@xotic.us</p>
Put the email address through object reference instead of directly putting it here.

Add period `.` at the end of the sentence.

2017-07-19 07:06 UTC, yostashiro commented on stock_delivery_notification/data/mail_template_data.xml
>          <field name="email_from">sales@xotic.us</field>
Should this be the sender?  Try using object reference in any case instead of directly putting in the address.

2017-07-19 07:06 UTC, yostashiro commented on stock_delivery_notification/data/mail_template_data.xml
> +        <field name="reply_to">sales@xotic.us</field>
Try using object reference in any case instead of directly putting in the address.

2017-07-19 07:39 UTC, TimLai125 commented on stock_delivery_notification/models/stock_picking.py
> +            picking.date_done_ctx = datetime_done_ctx.strftime("%Y-%m-%d %H:%M:%S %Z")
But the to_string method does not show timezone info of the datetime

2017-07-19 07:41 UTC, yostashiro commented on stock_delivery_notification/models/stock_picking.py
> +            picking.date_done_ctx = datetime_done_ctx.strftime("%Y-%m-%d %H:%M:%S %Z")
OK, then.  👍

2017-07-19 12:23 UTC, TimLai125 commented on stock_delivery_notification/models/stock_picking.py
> +        email_from = self.env['ir.mail_server'].search(
Here I assumed the name of the registered outgoing server is an email address

2017-07-19 12:23 UTC, TimLai125 commented on stock_delivery_notification/data/mail_template_data.xml
> +        <field name="email_from"><![CDATA["${object.company_id.name}" <${ctx.get('email_from')}>]]></field>
Maybe we could stick to the previous commit, which could keep things simpler

2017-07-19 12:23 UTC, TimLai125 commented
Sorry that I forgot to submit the review

2017-07-22 12:10 UTC, yostashiro commented
Taken over by https://github.com/rfhk/cip-custom/pull/60.

2017-07-22 12:10 UTC, closed without merging