Add multi-website features to Email templates
rfhk/cip-customization pull request #84
Opened 2017-10-09 10:36 UTC by TimLai125

2017-10-09 10:42 UTC, TimLai125 commented
@yostashiro The PR is ready to review.

2017-10-10 00:44 UTC, yostashiro requested changes

2017-10-10 00:44 UTC, yostashiro commented on mail_multi_website_email/models/res_partner_hook_get_signup_url_for_action.py
> +            ('partner_id', '=', partner.id)
No need to include `(active, '=', True)`?  I guess it is technically possible to link multiple users to a partner although it shouldn't happen under normal circumstances.

2017-10-10 00:44 UTC, yostashiro commented on stock_delivery_notification/__manifest__.py
> +    'version': '10.0.1.2.3',
`'10.0.1.2.0'`

2017-10-10 00:44 UTC, yostashiro commented on stock_delivery_notification/models/stock_picking.py
> +                        ('partner_id', '=', sale_order.partner_id.id)
No need to include `('active', '=', False)`?

2017-10-10 02:42 UTC, TimLai125 commented
@yostashiro I have changed the implementation in the sale_order, i.e. override the get_access_action method to add the domain url hence overwriting the default email template is not needed.

2017-10-10 06:34 UTC, yostashiro approved these changes
👍

2017-10-12 06:53 UTC, merged