[ADD] sale_order_cancel_adj
rfhk/cip-customization pull request #85
Opened 2017-10-11 06:12 UTC by TimLai125

2017-10-11 06:16 UTC, TimLai125 commented
@yostashiro Please review the PR. 
There will be still orphaned stock.picking yet all of them will be in "cancel" state.

2017-10-16 05:26 UTC, yostashiro requested changes

2017-10-16 05:26 UTC, yostashiro commented on sale_order_cancel_adj/models/sale_order.py
> +    def action_cancel(self):
Can you insert the related Github issue for reference?

2017-10-16 11:40 UTC, yostashiro approved these changes

2017-10-17 02:24 UTC, merged